#!/bin/bash

# Add default gateway so we can download stuff
mkdir -p ~/Downloads/
cd ~/Downloads

# Download the configuration files
wget https://ilab2.net.in.tum.de/courses/material/ilab2_mini_dane_tlsa/db.ilabbank.com
wget https://ilab2.net.in.tum.de/courses/material/ilab2_mini_dane_tlsa/named.conf.local
wget https://ilab2.net.in.tum.de/courses/material/ilab2_mini_dane_tlsa/named.conf.options

# Move them to their places
sudo mv named.conf.local /etc/bind/named.conf.local
sudo mv named.conf.options /etc/bind/named.conf.options
sudo mv db.ilabbank.com /etc/bind/db.ilabbank.com

# Start bind
sudo service bind9 start

